- name: install repmgr
  sudo: true
  apt: pkg="{{item}}" state=present force=true update_cache=yes
  with_items:
    - repmgr
    - "postgresql-{{postgresql_version}}-repmgr"
    - "postgresql-contrib-{{postgresql_version}}"
